### ISSUE TITLE
Finalize data sets by April 24

### ISSUE THREAD

**Issue by preetijuturu** [preetijuturu/p280s21project3#2]

**Comment by sjsrey** [comment]
Elementary School Districts: http://www2.census.gov/geo/tiger/TIGER2010DP1/ELSD_2010Census_DP1.zip

**Comment by sjsrey** [comment]
https://www.census.gov/programs-surveys/saipe/technical-documentation/methodology/school-districts/overview-school-district.html

**Comment by sjsrey** [comment]
See the boundary files on this page: https://www.census.gov/geographies/mapping-files/2010/geo/tiger-data.html

![image](https://user-images.githubusercontent.com/118042/116497947-6c758c80-a85d-11eb-834f-0e5c6653e9d5.png)
