### ISSUE TITLE
Unable to have two legends on map

### ISSUE THREAD

**Issue by preetijuturu** [preetijuturu/p280s21project3#39]
See [EJ_Visualization.ipynb](https://github.com/preetijuturu/p280s21project3/blob/main/EJ_Visualization.ipynb) and the issue with plotting the CEDA school outcomes with the EJ/ACA data within the NCES district boundaries; Step 8, Line 9

![Issue Image](https://user-images.githubusercontent.com/67488061/119074640-3cc12c80-b9a4-11eb-9b2c-5adb1172fb1d.png)

**Comment by WawNun** [comment]
Slightly better visuals as it removes the whites in the map - still figure out the legent issues.
```
f, ax = plt.subplots(1, figsize=(9, 9))
rusd_ej.plot(ax=ax, column='D_RESP_2', legend=True, scheme='Quantiles', legend_kwds={'fmt':'{:.0f}'},  \
         cmap='RdYlBu' , edgecolor='k')
rusd_schools.plot(ax=ax, column='gcs_mn_avg_ol', legend=True, scheme='Quantiles', legend_kwds={'fmt':'{:.0f}'}, \
         cmap='viridis', edgecolor='k')
ax.set_axis_off()
ax.set_title('EPA EJSCREEN FOR RUSD')
plt.axis('equal')
plt.show()

```

**Comment by lsala010** [comment]
Thank you for sharing the coding I was still figuring out the code part :)

**Comment by preetijuturu** [comment]
[Resource for generating 2 legends](https://stackoverflow.com/questions/12761806/matplotlib-2-different-legends-on-same-graph)

**Comment by WawNun** [comment]
Useful links provided during the class 
https://stackoverflow.com/questions/51549804/how-to-plot-two-maps-side-by-side-using-pysal-or-geopandas
https://stackoverflow.com/questions/63005381/how-to-show-both-colormaps-in-the-legend-in-geopandas

**Comment by lsala010** [comment]
![attempt_2_legend_rusd_ef plot](https://user-images.githubusercontent.com/75343711/119846441-bfc81280-becf-11eb-8de1-0027cd3d9b48.png)

**Comment by lsala010** [comment]
first three lines are what the professor helped with, he recommended that maybe we should look at the legends side by side. But if we figure out the coding to do everything together then that won't be a concern.  
I have added a file on the repo called legend that specifically shows what we have trouble shooted.

**Comment by lsala010** [comment]
![1st_legend_attempt ](https://user-images.githubusercontent.com/75343711/119847591-b68b7580-bed0-11eb-963a-c3e2204d7e1f.png)

**Comment by lsala010** [comment]
this graph shows how not all the legends are showing

**Comment by WawNun** [comment]
Thanks for sharing will take a look, I think we can get rid of the legend_kwds code part and make it simple and do the one which had the legs instead.
